# Generated by Django 3.0.2 on 2020-06-06 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SamlProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('issuer_id', models.CharField(max_length=200)),
                ('saml_subject', models.CharField(max_length=200)),
                ('audience_id', models.CharField(max_length=200)),
                ('acs_endpoint', models.CharField(max_length=200)),
                ('last_updated_date', models.DateTimeField(auto_now_add=True, verbose_name='last updated')),
            ],
        ),
        migrations.CreateModel(
            name='SamlProfileAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=200)),
                ('attribute_value', models.CharField(max_length=200)),
                ('saml_profile_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='saml_post.SamlProfile')),
            ],
        ),
    ]
