# Generated by Django 3.0.2 on 2020-07-12 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saml_post', '0001_added_saml_profile_and_saml_profile_attribute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samlprofile',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
